version: '3'

services:
  mysql:
    platform: linux/amd64
    image: mysql:latest
    container_name: daily-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "DailyOneStep"
      TZ: Asia/Seoul
    volumes:
      - "./mysql/conf.d:/etc/mysql/conf.d"